site_name: IntelliJ IDEA Setup Guide for CST Students
site_url: https://kjalloway.github.io/COMM2216_User_Documentation_Project_KJA_DLN/
repo_url: https://github.com/KJAlloway/COMM2216_User_Documentation_Project_KJA_DLN
repo_name: KJAlloway/COMM2216_User_Documentation_Project_KJA_DLN

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - search.highlight
    - search.suggest
    - toc.follow

nav:
  - Introduction: index.md
  - Installation and Student Account Setup: installation.md
  - Installing and Configuring Plugins: plugins.md
  - Configuring Inspections: inspections.md
  - Keyboard Shortcuts: shortcuts.md
  - Configuring Code Templates: templates.md
  - Glossary: glossary.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
